#ifndef PORTABLE_WORDSIZES
#ifdef __MW_TARGET_USE_HARDWARE_RESOURCES_H__
#ifndef __MW_TARGET_HARDWARE_RESOURCES_H__
#define __MW_TARGET_HARDWARE_RESOURCES_H__

#define MW_MULTI_TASKING_MODE 1
#include "main.h"
#include "SysTickScheduler.h"
#include "arm_cortex_m_multitasking.h"

#define MW_USECODERTARGET 1
#define MW_TARGETHARDWARE STM32F4xx Based
#define MW_CONNECTIONINFO_SERIAL_BAUDRATE stm32cube.codegen.getConnectivityBaudrate(hCS)
#define MW_CONNECTIONINFO_SERIAL_COMPORT stm32cube.codegen.getConnectivityCOMPort(hCS)
#define MW_CONNECTIONINFO_SERIAL_VERBOSE 1
#define MW_EXTMODE_CONFIGURATION serial
#define MW_EXTMODE_SIGNALBUFFERSIZE 2048.000000
#define MW_EXTMODE_USEREALTIMESTAMPLOGGING 1
#define MW_EXTMODE_RUNNING on
#define MW_RTOS Baremetal
#define MW_RTOSBASERATETASKPRIORITY 40
#define MW_SCHEDULER_INTERRUPT_SOURCE 0
#define MW_RUNTIME_BUILDACTION 1
#define MW_RUNTIME_RUNTIMELIBRARY 0
#define MW_RUNTIME_DISABLEPARALLELBUILD 0
#define MW_STM32CUBEMX_PROJECTFILEBUTTON 
#define MW_STM32CUBEMX_CREATEPROJECTFILEBUTTON 
#define MW_STM32CUBEMX_LAUNCHPROJECTFILEBUTTON 
#define MW_STM32CUBEMX_PROJECTFILE D:/stm32/cubemx_project/MBD_Tran/MBD_Tran.ioc
#define MW_STM32CUBEMX_DEVICEID STM32F407V(E-G)Tx
#define MW_STM32CUBEMX_FAMILY STM32F4
#define MW_STM32CUBEMX_CONNECTIVITYMODE 0
#define MW_STM32CUBEMX_AUTODETECTBOARD 0
#define MW_STM32CUBEMX_DEVICELIST -1
#define MW_STM32CUBEMX_DEVICELISTREFRESH 
#define MW_CLOCKING_CPUCLOCKRATEMHZ 16.000000
#define MW_CONNECTION_SERIALMODULE 0
#define MW_CONNECTION_SERIALPORT COM13
#define MW_USART_USART1CONFIGUREMODULE 48
#define MW_USART_USART1TRANSMITMODE 0
#define MW_USART_USART1RECEIVEMODE 0
#define MW_USART_USART1TRANSMITBUFFERLENGTH 128
#define MW_USART_USART1RECEIVEBUFFERLENGTH 128
#define MW_USART_USART1DISABLEDMAINTERRUPTONERROR 48
#define MW_USART_USART2CONFIGUREMODULE 48
#define MW_USART_USART2TRANSMITMODE 0
#define MW_USART_USART2RECEIVEMODE 0
#define MW_USART_USART2TRANSMITBUFFERLENGTH 128
#define MW_USART_USART2RECEIVEBUFFERLENGTH 128
#define MW_USART_USART2DISABLEDMAINTERRUPTONERROR 48
#define MW_USART_USART3CONFIGUREMODULE 48
#define MW_USART_USART3TRANSMITMODE 0
#define MW_USART_USART3RECEIVEMODE 0
#define MW_USART_USART3TRANSMITBUFFERLENGTH 128
#define MW_USART_USART3RECEIVEBUFFERLENGTH 128
#define MW_USART_USART3DISABLEDMAINTERRUPTONERROR 48
#define MW_USART_UART4CONFIGUREMODULE 48
#define MW_USART_UART4TRANSMITMODE 0
#define MW_USART_UART4RECEIVEMODE 0
#define MW_USART_UART4TRANSMITBUFFERLENGTH 128
#define MW_USART_UART4RECEIVEBUFFERLENGTH 128
#define MW_USART_UART4DISABLEDMAINTERRUPTONERROR 48
#define MW_USART_UART5CONFIGUREMODULE 48
#define MW_USART_UART5TRANSMITMODE 0
#define MW_USART_UART5RECEIVEMODE 0
#define MW_USART_UART5TRANSMITBUFFERLENGTH 128
#define MW_USART_UART5RECEIVEBUFFERLENGTH 128
#define MW_USART_UART5DISABLEDMAINTERRUPTONERROR 48
#define MW_USART_USART6CONFIGUREMODULE 48
#define MW_USART_USART6TRANSMITMODE 0
#define MW_USART_USART6RECEIVEMODE 0
#define MW_USART_USART6TRANSMITBUFFERLENGTH 128
#define MW_USART_USART6RECEIVEBUFFERLENGTH 128
#define MW_USART_USART6DISABLEDMAINTERRUPTONERROR 48
#define MW_USART_UART7CONFIGUREMODULE 48
#define MW_USART_UART7TRANSMITMODE 0
#define MW_USART_UART7RECEIVEMODE 0
#define MW_USART_UART7TRANSMITBUFFERLENGTH 128
#define MW_USART_UART7RECEIVEBUFFERLENGTH 128
#define MW_USART_UART7DISABLEDMAINTERRUPTONERROR 48
#define MW_USART_UART8CONFIGUREMODULE 48
#define MW_USART_UART8TRANSMITMODE 0
#define MW_USART_UART8RECEIVEMODE 0
#define MW_USART_UART8TRANSMITBUFFERLENGTH 128
#define MW_USART_UART8RECEIVEBUFFERLENGTH 128
#define MW_USART_UART8DISABLEDMAINTERRUPTONERROR 48
#define MW_ADC1_USEDMA 0
#define MW_ADC1_USEWATCHDOG 0
#define MW_ADC1_EOCENABLEINTERRUPT 0
#define MW_ADC1_JEOCENABLEINTERRUPT 48
#define MW_ADC1_OVRENABLEINTERRUPT 48
#define MW_ADC1_PROJECTFILEBUTTON 
#define MW_ADC2_USEDMA 0
#define MW_ADC2_USEWATCHDOG 0
#define MW_ADC2_EOCENABLEINTERRUPT 0
#define MW_ADC2_JEOCENABLEINTERRUPT 48
#define MW_ADC2_OVRENABLEINTERRUPT 48
#define MW_ADC2_PROJECTFILEBUTTON 
#define MW_ADC3_USEDMA 0
#define MW_ADC3_USEWATCHDOG 0
#define MW_ADC3_EOCENABLEINTERRUPT 0
#define MW_ADC3_JEOCENABLEINTERRUPT 48
#define MW_ADC3_OVRENABLEINTERRUPT 48
#define MW_ADC3_PROJECTFILEBUTTON 
#define MW_TIMER_TIMERGROUP 0
#define MW_TIMER_TIM1CONFIGUREMODULE 48
#define MW_TIMER_TIM8CONFIGUREMODULE 48
#define MW_TIMER_TIM2CONFIGUREMODULE 48
#define MW_TIMER_TIM3CONFIGUREMODULE 48
#define MW_TIMER_TIM4CONFIGUREMODULE 48
#define MW_TIMER_TIM5CONFIGUREMODULE 48
#define MW_TIMER_TIM6CONFIGUREMODULE 48
#define MW_TIMER_TIM7CONFIGUREMODULE 48
#define MW_TIMER_TIM9CONFIGUREMODULE 48
#define MW_TIMER_TIM10CONFIGUREMODULE 48
#define MW_TIMER_TIM11CONFIGUREMODULE 48
#define MW_TIMER_TIM12CONFIGUREMODULE 48
#define MW_TIMER_TIM13CONFIGUREMODULE 48
#define MW_TIMER_TIM14CONFIGUREMODULE 48
#define MW_TIM1_STARTTIMER 49
#define MW_TIM1_TRIGGERINTERRUPT 48
#define MW_TIM1_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM1_CAPTURECOMPARE2INTERRUPT 48
#define MW_TIM1_CAPTURECOMPARE3INTERRUPT 48
#define MW_TIM1_CAPTURECOMPARE4INTERRUPT 48
#define MW_TIM1_UPDATEINTERRUPT 48
#define MW_TIM1_BREAKINTERRUPT 48
#define MW_TIM1_COMINTERRUPT 48
#define MW_TIM8_STARTTIMER 49
#define MW_TIM8_TRIGGERINTERRUPT 48
#define MW_TIM8_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM8_CAPTURECOMPARE2INTERRUPT 48
#define MW_TIM8_CAPTURECOMPARE3INTERRUPT 48
#define MW_TIM8_CAPTURECOMPARE4INTERRUPT 48
#define MW_TIM8_UPDATEINTERRUPT 48
#define MW_TIM8_BREAKINTERRUPT 48
#define MW_TIM8_COMINTERRUPT 48
#define MW_TIM2_STARTTIMER 49
#define MW_TIM2_TRIGGERINTERRUPT 48
#define MW_TIM2_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM2_CAPTURECOMPARE2INTERRUPT 48
#define MW_TIM2_CAPTURECOMPARE3INTERRUPT 48
#define MW_TIM2_CAPTURECOMPARE4INTERRUPT 48
#define MW_TIM2_UPDATEINTERRUPT 48
#define MW_TIM3_STARTTIMER 49
#define MW_TIM3_TRIGGERINTERRUPT 48
#define MW_TIM3_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM3_CAPTURECOMPARE2INTERRUPT 48
#define MW_TIM3_CAPTURECOMPARE3INTERRUPT 48
#define MW_TIM3_CAPTURECOMPARE4INTERRUPT 48
#define MW_TIM3_UPDATEINTERRUPT 48
#define MW_TIM4_STARTTIMER 49
#define MW_TIM4_TRIGGERINTERRUPT 48
#define MW_TIM4_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM4_CAPTURECOMPARE2INTERRUPT 48
#define MW_TIM4_CAPTURECOMPARE3INTERRUPT 48
#define MW_TIM4_CAPTURECOMPARE4INTERRUPT 48
#define MW_TIM4_UPDATEINTERRUPT 48
#define MW_TIM5_STARTTIMER 49
#define MW_TIM5_TRIGGERINTERRUPT 48
#define MW_TIM5_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM5_CAPTURECOMPARE2INTERRUPT 48
#define MW_TIM5_CAPTURECOMPARE3INTERRUPT 48
#define MW_TIM5_CAPTURECOMPARE4INTERRUPT 48
#define MW_TIM5_UPDATEINTERRUPT 48
#define MW_TIM6_STARTTIMER 49
#define MW_TIM6_UPDATEINTERRUPT 48
#define MW_TIM7_STARTTIMER 49
#define MW_TIM7_UPDATEINTERRUPT 48
#define MW_TIM9_STARTTIMER 49
#define MW_TIM9_TRIGGERINTERRUPT 48
#define MW_TIM9_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM9_CAPTURECOMPARE2INTERRUPT 48
#define MW_TIM9_UPDATEINTERRUPT 48
#define MW_TIM10_STARTTIMER 49
#define MW_TIM10_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM10_UPDATEINTERRUPT 48
#define MW_TIM11_STARTTIMER 49
#define MW_TIM11_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM11_UPDATEINTERRUPT 48
#define MW_TIM12_STARTTIMER 49
#define MW_TIM12_TRIGGERINTERRUPT 48
#define MW_TIM12_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM12_CAPTURECOMPARE2INTERRUPT 48
#define MW_TIM12_UPDATEINTERRUPT 48
#define MW_TIM13_STARTTIMER 49
#define MW_TIM13_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM13_UPDATEINTERRUPT 48
#define MW_TIM14_STARTTIMER 49
#define MW_TIM14_CAPTURECOMPARE1INTERRUPT 48
#define MW_TIM14_UPDATEINTERRUPT 48
#define MW_DATAVERSION 2016.02
#define MW_STM32_ANALOGINPUT_ID 44

#endif /* __MW_TARGET_HARDWARE_RESOURCES_H__ */

#endif

#endif
